language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests at all"

script:
  - docker --version # print the version for logging
  - docker build -t reverseproxy ./project/udagram-reverseproxy
  - docker build -t udagram-api-user ./project/udagram-api-user
  - docker build -t udagram-api-feed ./project/udagram-api-feed
  - docker build -t udagram-frontend ./project/udagram-frontend
  
  - docker tag reverseproxy jalvarezdv/reverseproxy:v1
  - docker tag udagram-api-user jalvarezdv/udagram-api-user:v1
  - docker tag udagram-api-feed jalvarezdv/udagram-api-feed:v1
  - docker tag udagram-frontend jalvarezdv/udagram-frontend:v1

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push jalvarezdv/reverseproxy:v1
  - docker push jalvarezdv/udagram-api-user:v1
  - docker push jalvarezdv/udagram-api-feed:v1
  - docker push jalvarezdv/udagram-frontend:v1
